---
title: "STAT345 - FINAL PROJECT"
author: "Ava Woodruff, Marisa Percey, Ethan Leader, Layne Peters"
date: "2026-04-21"
output: html_document
---

``` {r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

``` {r libraries}
# adds libraries
library(rvest)
library(tidyverse)
library(purrr)
```

``` {r source}
# WIKIPEDIA: SOURCED BILLBOARD LINKS
# sets desired years to extract data from
years <- c(1959:2025)

# concatenates urls with the years 
billboard.links <- str_c("https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_", years)
```

``` {r functions}
# FUNCTION: SCRAPING EACH BILLBOARD YEAR FOR INFORMATION AND SONG LINKS

# takes in url and extracts the rank, title, and artist for the top 100 songs for that year
# returns a tibble w/ the rank, title, and artist
scrape.year = function(url) {
  
  # reads url
  billboard.page = read_html(url)
  
  # adds message to print out progress of scraping
  year = str_extract(url, "[0-9]{4}")
  message("Scraping: ", year)
  
  # sets timer to "sleep" between scrapes, trying to be nice to wikipedia :)
  Sys.sleep(1)
  
  # gets url to each song from wikipedia
  # sets songs w/o links to NA
  song.links = billboard.page %>%
    html_elements("table.wikitable tr") %>% .[-1] %>%
    map_chr(~ {
      link = .x %>% html_element("td:nth-child(2) a") %>% html_attr("href")
      if(is.na(link)) 
        NA_character_
      else 
        str_c("https://en.wikipedia.org", link)})
  
  # creates tibble w/ rank (renamed from № and No.), title, and artist
  billboard.page %>%
    html_element("table.wikitable") %>%
    html_table() %>%
    as_tibble() %>%
    rename_with(~ "rank.col", any_of(c("№", "No."))) %>%
    mutate(year = year, wiki.url = song.links) %>%
    select(year, rank = rank.col, title = `Title`, artist = `Artist(s)`, wiki.url)
}


# FUNCTION: BUILDING SONGLYRICS URL PATH, SCRAPING LYRICS

# takes in artist and title from billboard.page tibble
# returns url to the songlyrics page and the lyrics for each song
scrape.songlyrics = function(artist, title) {
  
  # cleans and standardizes artists
  artist.clean = artist %>%
    str_to_lower() %>%
    str_replace_all("&", "and") %>%
    str_replace_all("[^a-z0-9]", "-") %>%
    str_replace_all("-+", "-") %>%
    str_remove("^-") %>%
    str_remove("-$")
  
  # cleans and standardizes titles
  title.clean = title %>%
    str_to_lower() %>%
    str_replace_all("&", "and") %>%
    str_replace_all("[^a-z0-9]", "-") %>%
    str_replace_all("-+", "-") %>%
    str_remove("^-") %>%
    str_remove("-$")
  
  # builds songlyrics url
  songlyrics.url = str_c("https://www.songlyrics.com/", artist.clean, "/", title.clean, "-lyrics/")
  
  # status iteration message  w/ pausing requests
  # sets timer to "sleep" between scrapes, trying to be nice to wikipedia :)
  i <<- i + 1
  if (i %% 100 == 0) {
    message("Pausing... ", i)
    Sys.sleep(60)
  } else {
    message("Validating Row ", i, ": ", songlyrics.url)
    Sys.sleep(0.5)
  }
  
  # validating and scraping supposed url
  tryCatch({
    songlyrics.page = read_html(songlyrics.url)
    
    # querying/searching page for lyrics marker, scraping
    lyrics = songlyrics.page %>%
      html_element("#songLyricsDiv") %>%
      html_text2()
    
    # sets NA if no lyrics found
    if (is.na(lyrics)) {
      list(songlyrics.url = NA_character_, lyrics = NA_character_)
    } else {
        list(songlyrics.url = songlyrics.url, lyrics = lyrics)
    }
  }, error = function(e) {
      list(songlyrics.url = NA_character_, lyrics = NA_character_)
  })
}
```

``` {r extraction}
# scrapes the hot 100 songs for provided years (1959-2025) and binds all data into one table
hot100.raw = billboard.links %>%
  map(scrape.year) %>%
  list_rbind()
```

``` {r}
# scrape song lyrics for the top 10 songs for each year, then separate url from lyrics
i = 0
hot100.top10 = hot100.raw %>%
  filter(rank <= 10) %>%
  mutate(results = map2(artist, title, scrape.songlyrics)) %>%
  unnest_wider(results)
```

```{r}
# testing one url
wiki.url = hot100.raw$wiki.url[1]

# reads url
page = read_html(wiki.url)
rows = page %>%
  html_elements(".infobox tr") %>%
  html_text2()
rows

# gets song's length, label, and genre 
rows %>% str_subset("Length")
rows %>% str_subset("Label")
rows %>% str_subset("Genre|Genres")


# FUNCTION: SCRAPING FOR ADDITIONAL SONG INFORMATION

# takes in a url and scrapes the site for the song length, label, and genre(s)
# returns a list of the length, label, and genre for each song
scrape.wiki = function(wiki.url) {
  
  tryCatch({
    
    page = read_html(wiki.url)
    
    rows = page %>%
      html_elements(".infobox tr") %>%
      html_text2()
    
    get_one <- function(x, pattern, remove_pattern = pattern) {
      val <- x %>%
        str_subset(pattern) %>%
        str_remove(remove_pattern) %>%
        str_trim()
      
      if (length(val) == 0) return(NA_character_)
      val[1]   # ALWAYS take just one
    }
    
    list(
      song.length = get_one(rows, "Length"),
      label       = get_one(rows, "Label"),
      genre       = rows %>%
        str_subset("Genre|Genres") %>%
        str_remove("Genre|Genres") %>%
        str_replace_all("\\[[0-9]+\\]", "") %>%
        str_replace_all("\n", ", ") %>%
        str_squish() %>%
        { if (length(.) == 0) NA_character_ else .[1] }
    )
    
  }, error = function(e) {
    
    list(
      song.length = NA_character_,
      label = NA_character_,
      genre = NA_character_
    )
  })
}
```

```{r}
# apply scraper and add columns to tibble
hot100.top10 <- hot100.raw %>%
  filter(rank <= 10) %>%
  mutate(wiki.results = purrr::map(wiki.url, scrape.wiki)) %>%
  tidyr::unnest_wider(wiki.results)
```

```{r}
scrape.wiki(hot100.raw$wiki.url[1])
```
