---
title: "STAT345 - FINAL PROJECT"
author: "Ava Woodruff, Marissa Percey, Ethan Leader, Layne Peters"
date: "2026-04-21"
output: html_document
---

``` {r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

``` {r libraries}
library(rvest)
library(tidyverse)
```

``` {r source}
# WIKIPEDIA: SOURCED BILLBOARD LINKS
billboard.links = read_html("https://en.wikipedia.org/wiki/Category:Lists_of_Billboard_Year-End_Hot_100_singles") %>%
  html_elements("#mw-pages a") %>%
  html_attr("href") %>%
  keep(~ str_detect(.x, "Billboard_Year-End_Hot_100_singles_of_[0-9]{4}$")) %>%
  str_c("https://en.wikipedia.org", .)
```

``` {r functions}
# FUNCTION: SCRAPING EACH BILLBOARD YEAR FROM BILLBOARD.LINKS
# Takes URL--Billboard Top 100 (Year)--extracts the wikitable
# Returns tibble w/ year, rank, title, artist, and wiki.url--the embedded wikipedia link to each song for further scraping information.
scrape.year = function(url) {
  # READ URL
  billboard.page = read_html(url)
  
  # MESSAGE PRINTS OUT PROGRESS OF SCRAPING BILLBOARDS
  year = str_extract(url, "[0-9]{4}")
  message("Scraping: ", year)
  
  # SETS TIMER TO "SLEEP" BETWEEN SCRAPES
  Sys.sleep(1)
  
  # EXTRACTS URL OF EACH SONG FROM WIKIPEDIA
  song.links = billboard.page %>%
    html_elements("table.wikitable tr") %>%
    # DROP THE TABLE HEADER
    .[-1] %>%
    map_chr(~ {
      link = .x %>% html_element("td:nth-child(2) a") %>% html_attr("href")
      # SETS SONGS W/O WIKIPEDIA PAGES/EMBEDDED LINKS TO N/A
      if(is.na(link)) 
        NA_character_
      else 
        str_c("https://en.wikipedia.org", link)})
  
  # CREATES TIBBLE W/ RANK (RENAMED FROM № and No.), ARTIST, AND TITLE
  billboard.page %>%
    html_element("table.wikitable") %>%
    html_table() %>%
    as_tibble() %>%
    # CATCH RANK DISCREPANCIES OF WIKITABLE
    rename_with(~ "rank.col", any_of(c("№", "No."))) %>%
    # ADD YEAR AND WIKI.URL COLUMNS TO TIBBLE
    mutate(year = year, wiki.url = song.links) %>%
    select(year, rank = rank.col,  artist = `Artist(s)`, title = `Title`, wiki.url)
}

# FUNCTION: BUILDING SONGLYRICS URL PATH, SCRAPING LYRICS FROM SOURCE
# Takes artist and title from our tibble of extracted wikipedia billboard tables.
# Returns songlyrics URL and lyrics of billboard songs, upon successful replication of URL schema and finds lyrics page--lyrics html element.
scrape.songlyrics = function(artist, title) {
  # HELPER FUNCTIONS
  # CLEAN AND STANDARDIZE EXPRESSION (ARTIST, TITLE)
  clean.string = function(x) {
    x %>%
      str_remove("/.*$") %>%
      str_to_lower() %>%
      str_replace_all("&", "") %>%
      str_replace_all("part\\s+([0-9]+)", "pt-\\1") %>% 
      str_replace_all("part\\s+(i{1,3}|iv|vi{0,3}|ix)", "pt-\\1") %>%
      str_replace_all("[^a-z0-9]", "-") %>%
      str_replace_all("-+", "-") %>%
      str_remove("^-") %>%
      str_remove("-$")
  }
  
  # ATTEMPT TO SCRAPE LYRICS FROM URL
  try.scrape = function(url) {
    tryCatch({
      songlyrics.page = read_html(url)
      # QUERYING/SEARCHING PAGE FOR LYRICS ELEMENT
      lyrics = songlyrics.page %>%
        html_element("#songLyricsDiv") %>%
        html_text2()
      if (is.na(lyrics)) NULL
      else list(songlyrics.url = url, lyrics = lyrics)
    }, error = function(e) NULL)
  }
  
  # STATUS/ITERATION MESSAGE W/PAUSING REQUESTS
  # SETS TIMER TO "SLEEP" BETWEEN SCRAPES
  i <<- i + 1
  if (i %% 100 == 0) {
    message("Pausing... ", i)
    Sys.sleep(60)
  } else {
    Sys.sleep(5)
  }
  message("Validating ", i, ": ", artist, " - ", title)
  
  # CLEAN STRINGS
  artist.clean = clean.string(artist)
  title.clean = clean.string(title)
  
  # BUILD PRIMARY URL (W/ FULL ARTIST CONTEXT)
  primary.url = str_c("https://www.songlyrics.com/", artist.clean, "/", title.clean, "-lyrics/")
  # BUILD SECONDARY URL (W/O "FEATURED" ARTIST)
  without.featured = artist %>%
    str_remove_all(regex("\\s*featuring.*$", ignore_case = TRUE)) %>%
    clean.string()
  secondary.url = str_c("https://www.songlyrics.com/", without.featured, "/", title.clean, "-lyrics/")
  # BUILD TERTIARY URL (W/O "AND" ARTIST)
  without.and = artist %>%
    str_remove_all(regex("\\s*and.*$", ignore_case = TRUE)) %>%
    clean.string()
  tertiary.url = str_c("https://www.songlyrics.com/", without.and, "/", title.clean, "-lyrics/")
  # BUILD QUATERNARY URL (W/O "," ARTIST)
  without.comma = artist %>%
    str_remove_all(regex(",.*$", ignore_case = TRUE)) %>%
    clean.string()
  quaternary.url = str_c("https://www.songlyrics.com/", without.comma, "/", title.clean, "-lyrics/")
  
  # PRIMARY ATTEMPT
  result = try.scrape(primary.url)
  # SECONDARY ATTEMPT
  if (is.null(result)) result = try.scrape(secondary.url)
  # TERTIARY ATTEMPT
  if (is.null(result)) result = try.scrape(tertiary.url)
  # QUATERNARY ATTEMPT
  if (is.null(result)) result = try.scrape(quaternary.url)
  
  if (is.null(result)) {
    list(songlyrics.url = NA_character_, lyrics = NA_character_)
  } else {
    result
  }
}

# FUNCTION: SCRAPING ADDITIONAL SONG INFORMATION WIKIPEDIA SONG PAGES STORED AS WIKI.URL
# Takes URL--wiki.url--extracts the wikipedia infobox with peripheral information.
# Returns a list including length, label, genre of song through scraping.
scrape.wiki = function(url) {
  # SKIP NAs
  if (is.na(url)) 
    return(list(
      song.length = NA_character_,
      song.label = NA_character_,
      song.genre = NA_character_))
  
  # ITERATION MESSAGE
  Sys.sleep(1)
  message("Scraping: ", url)
  
  tryCatch({
    song.page = read_html(url)
    
    wiki.infobox = song.page %>%
      html_elements(".infobox tr") %>%
      html_text2()
    
    # HELPER FUNCTION
    # SEARCHES INFOBOX FOR EXPRESSION 
    parse.infobox = function(x, pattern, remove_pattern = pattern) {
      # EXTRACT EVERYTHING ELSE EXCEPT EXPRESSION 
      infobox.label = x %>%
        str_subset(pattern) %>%
        str_remove(remove_pattern) %>%
        str_trim()
      # NOT IN INFOBOX, NA
      if (length(infobox.label) == 0) return(NA_character_)
      # RETURN JUST ONE
      infobox.label[1]
    }
    
    # EXTRACTION
    list(
      song.length = parse.infobox(wiki.infobox, "Length"),
      song.label = parse.infobox(wiki.infobox, "Label"),
      song.genre = wiki.infobox %>%
        str_subset("Genre|Genres") %>%
        str_remove("Genre|Genres") %>%
        str_replace_all("\\[[0-9]+\\]", "") %>%
        str_replace_all("\n", ", ") %>%
        str_squish() %>%
        str_remove("^,\\s*") %>%
        { if (length(.) == 0) NA_character_ else .[1] })
    }, error = function(e) {
      list(
        song.length = NA_character_,
        song.label = NA_character_,
        song.genre = NA_character_
      )
  })
}

# FUNCTION:
# Takes
# Returns
title.measure = function() {
  
}

# FUNCTION:
# Takes
# Returns
phrase.measure = function() {

}
```

``` {r billboard}
# ALL BILLBOARD WIKITABLES, WIKIURLs TO SONGS
hot100.raw = billboard.links %>%
  map(scrape.year) %>%
  list_rbind()
```

```{r}
hot100.raw = hot100.raw %>%
  mutate(wiki.info = map(wiki.url, scrape.wiki)) %>%
  unnest_wider(wiki.info)

write_csv(hot100.raw, "hot100_raw.csv")
```

``` {r lyrics}
# TOP 10 FOR EACH YEAR
i = 0
hot100.full = hot100.raw %>%
  mutate(results = map2(artist, title, scrape.songlyrics)) %>%
  unnest_wider(results)

write_csv(hot100.full, "hot100_full.csv")

# RETRY NAs
i = 0
hot100.full[is.na(hot100.full$lyrics), ] = hot100.full %>%
  filter(is.na(lyrics)) %>%
  select(-c("songlyrics.url", "lyrics")) %>%
  mutate(results = map2(artist, title, scrape.songlyrics)) %>%
  unnest_wider(results)
```
